version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -e .

  build:
    commands:
      - echo Build started on `date`
      - echo Running module test
      - python -m src.components.data_ingestion || echo "No execution required"

artifacts:
  files:
    - '**/*'

